#!/bin/bash
# Useful git alias: 
#	'status --short --branch'
#	'push -f origin $(git rev-parse --abbrev-ref HEAD)'

declare -a arr=("repositories here") # TODO: extract this to separate file.

function run_git {
	echo "=================================================="
	echo "Repository: ${1}"
	git --git-dir "/mnt/c/workspace/${1}/.git" --work-tree="/mnt/c/workspace/${1}" "${@:2}"
}

for i in "${arr[@]}"
do
	run_git ${i} ${@}
done
